version: "3"
services:
  example:
    build: ./example/src/.
    ports:
    - "3000:3000"
  pormetheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus/config/:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
    - grafana-storage:/var/lib/grafana
    ports:
    - "3001:3000"
volumes:
  prometheus_data: {}
  grafana-storage: {}