version: "3"
services:
  example:
    build: ./example/src/.
    ports:
    - "3000:3000"
  pormetheus:
    build: ./prometheus/.
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
    - "3001:3000"