global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']
    
  - job_name: 'example'
    static_configs:
      - targets: ['example:3000']