global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    monitor: codelab-monitor

rule_files:

scrape_configs:
  - job_name: example
    static_configs:
      - targets:
        - example:3000

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: nginx
    static_configs:
      - targets:
        - nginx-exporter:4040